### ISSUE TITLE
How does the time picker works?

### ISSUE THREAD

**Issue by vivekebics** [mmazzarolo/react-native-modal-datetime-picker#107]
Hi. You have method to show the data picker alone. But in the sample you have given time picker also. How does it work ?

**Comment by mmazzarolo** [comment]
Hey @vivekebics, since this has been asked multiple times and I'm aware it was not clear enough in the REAMDE, I just added [the answer to your question in the FAQ section](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/master/README.md#how-do-you-show-the-timepicker-instead-of-the-datepicker).
