### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by Rafaell416** [mmazzarolo/react-native-modal-datetime-picker#128]
Is there a way to translate to other languages the date picked?

**Comment by mmazzarolo** [comment]
Hey @Rafaell416 , what do you mean exactly? Could you be a bit more specific? Thanks!

**Comment by Rafaell416** [comment]
Hi @mmazzarolo, thanks for answering . What I mean is, each time you open the modal for picking the date, its language depends on device language, but when you choose the date what you see is always the date in english, My question is how can i get the date picked at the modal in another language different to english ?, like french maybe.

**Comment by mmazzarolo** [comment]
@Rafaell416 If I understand correctly what your asking, your issue is more Javascript related then with `react-native-modal-datetime-picker` itself.  
For translating the picker date in another language you should take a look at libraries that manipulate Javascript dates like [Moment.js](https://momentjs.com/) or [date-fns](https://github.com/date-fns/date-fns).  
Let me know if any of them will work for you 👍
