### ISSUE TITLE
Change request: Dismiss on backdrop press by default on iOS

### ISSUE THREAD

**Issue by JochemWarmenhoven** [mmazzarolo/react-native-modal-datetime-picker#152]
Hi, I was wondering if it was possible to close the dateTime picker when pressing ouside of the modal. And if it is, how would i do that?

**Comment by mmazzarolo** [comment]
Hey!
Since on Android you can't do it (we are using the react-native DateTimePicker) we are not planning to support the feature on iOS.

**Comment by jhogervorst** [comment]
@mmazzarolo If I may ask—Why aren’t you planning to support this on iOS?

The default iOS behaviour is to dismiss action sheets when tapping on the grey background. As such, I think it would make sense to do that here as well.

I’ve fixed this myself using `reactNativeModalPropsIOS={{onBackdropPress: myHideMethod}}` for now, so it’s no big issue🙂 But it may still be a nice default behaviour.

**Comment by mmazzarolo** [comment]
@JochemWarmenhoven of course you can ask! 
There was a mistake in my post above, I meant `we are not planning to support the feature on Android`, not iOS.  
On iOS you can already do it using the prop you described but it would be nice making it a default if this is the default iOS behaviour 👍 
If you're willing to submit a PR I can review it, merge it and publish it this weekend with #225 ...
otherwise we can wait until I find some free time to work on it by myself (but I don't have any plan for it for now unfortunately 😬 )

**Comment by mmazzarolo** [comment]
Done! [7.4.0](https://github.com/mmazzarolo/react-native-modal-datetime-picker/releases/tag/v7.4.0)
