### ISSUE TITLE
The initial date is reset after onCancel

### ISSUE THREAD

**Issue by ocarreterom** [mmazzarolo/react-native-modal-datetime-picker#237]
When setting an initial date `date={initialDate}` and then press the cancel button, the date and time are reset to "now".

**Comment by mmazzarolo** [comment]
Thanks for reporting (even if you haven't followed the template! 👴 )
Looks like a bug related to [this line](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/f24ee4c8dd73d7a168f7f50c5fc18ab0789fa48b/src/CustomDatePickerIOS/index.js#L78).  
I *think* it should be `this.props.date` instead of `Date.now()`.  
Willing to submit a PR and check if it fixes the issue?

**Comment by basbase** [comment]
This seems to work:
`  _resetDate = () => {
    this.setState({
      date: this.props.date || new Date()
    });
  };
`

**Comment by ocarreterom** [comment]
@mmazzarolo sorry for don't follow the template. It was too much text 😞.
PR sent 🚀

**Comment by ocarreterom** [comment]
@basbase thanks for the snipet. I think `|| new Date()` is not necessary since defaults props avoid date to be `undefined`.
