### ISSUE TITLE
Change language without modifying AppDelegate.m

### ISSUE THREAD

**Issue by JaWoGit** [mmazzarolo/react-native-modal-datetime-picker#244]
## Ask your Question

Hi,

first off all, awesome library! Thanks for that. 
Is there a possibility to change the language without modify the AppDelegate.m file? Because I'm using Expo and, as far as I know, there is no possibility to change the AppDelegate.m? 

Any help would be appreciated!

Cheers,
Janik

**Comment by mmazzarolo** [comment]
👋 @JaWoGit , unfortunately this component just uses the original React-Native DatePicker under the hood, so you might wanna ask this question on StackOverflow or in the Expo forums since we're not in control of the native iOS component... and I'm not aware of any way to do without playing with the AppDelegate.m 🤔
