### ISSUE TITLE
Is it possible to call it without creating react component?

### ISSUE THREAD

**Issue by pie6k** [mmazzarolo/react-native-modal-datetime-picker#363]
Now I have to put it in views hierarchy somewhere.

Is there anyway to do it like

```tsx
<Button onClick={async () => {
  const result = await datepicker.show(options);
  // do something with result
}} />
```

**Comment by mmazzarolo** [comment]
Hey!
One of the main reasons to use this library is because it allows you to control the datetimepicker trough a controlled component. 
If you need a more programmatic approach, you can use the classic community datetimepicker or wrap this component in a Context/Event-system to invoke it programmatically from anywhere in your app.
