### ISSUE TITLE
How to clear the date value

### ISSUE THREAD

**Issue by take** [mmazzarolo/react-native-modal-datetime-picker#381]
Hi thanks for the awesome library :D 

Is there a way to remove the selected date value? :eyes: 

Thanks,

**Comment by mmazzarolo** [comment]
Hey! Please use StackOverflow for troubleshooting, thanks!

**Comment by take** [comment]
@mmazzarolo 

thanks for the response, actually this wasn't troubleshooting 👀 

are there any ways to add a "clear" button to the data picker? 🤔

**Comment by take** [comment]
oh wait I just found https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/250, looks like it's impossible for now...? 😨

**Comment by shye0000** [comment]
Heyyyy, I found this prop `neutralButtonLabel`, it does the magic although the name is a little confusing.
Here checkout the doc of @react-native-community/datetimepicker:
https://github.com/react-native-datetimepicker/datetimepicker#neutralbuttonlabel-optional-android-only
And luckily its also supported by this package too, since all extra props are passed down to the react native community picker.
Just do this:
```
<DateTimePicker
    mode="date"
    isVisible={open}
    date={value ? new Date(value) : undefined}
    onConfirm={handleConfirm}
    onCancel={handleClose}
    // Androind clear button
    neutralButtonLabel="Clear"
/>
```

**Comment by kendallroth** [comment]
To confirm though, this does not work on iOS, correct?
