### ISSUE TITLE
iOS device with dark mode on shows no items in picker

### ISSUE THREAD

**Issue by lukemcgregor** [mmazzarolo/react-native-modal-datetime-picker#458]
## Environment

```
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.03 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-18 | Google APIs ARM EABI v7a, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
  npmGlobalPackages:
    *react-native*: Not Found
```
## Platforms

iOS only

## Versions

- iOS: 13.6
- react-native-modal-datetime-picker: 8.8.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 2.6.1
- react-native: 0.62
- react: 16.11

## Description

When the picker is using default settings and the device is in dark mode the times dont show up in the date picker (I dug into it and it's because @react-native-community/datetimepicker is autodetecting darkmode and setting the text color to white). 

![image](https://user-images.githubusercontent.com/1284608/89489277-3808fe80-d7fe-11ea-890c-78ef1fcf5344.png)

## Reproducible Demo

Add the picker without specifying isDarkModeEnabled
Change the device sim to use dark mode (its in the dev menu in settings)
Open the modal and you cant see any dates (its just a white box as per screenshot above)

## How to fix
I think there are 2 options to fix this:

 - explicitly set the color on the child DateTimePicker, which should align with isDarkModeEnabled
 - remove isDarkModeEnabled and instead use `React.Appearance.getColorScheme()` to automatically pick the theme color.

**Comment by mmazzarolo** [comment]
Thanks @lukemcgregor for resurrecting the issue. 
The reason why this component is using the `isDarkModeEnabled` prop is because `getColorScheme` wasn't well supported before. 
At this point, since the community picker is also [using `useColorScheme`](https://github.com/react-native-community/datetimepicker/blob/aaa4bbf67162af28dd07a1465a57a11c3aa1c26b/example/App.js#L21) I don't see why not going for the second option you suggested and use `useColorScheme` as well... Not sure if I can work on it anytime soon, wanna submit a PR? I can review it and update the docs... otherwise I'll work on it as soon as I have some free time

**Comment by lukemcgregor** [comment]
Yeah that was my thinking too, shouldn't be a hard change to make

**Comment by XanderTenBoden** [comment]
I have a similar issue but in the opposite situation: On light mode the text is not visible, while it is in dark mode :D It used to work fine a earlier today but I also did some code changes in the app, so I am not curtain if this is due to the new release or because I am doing something wrong. Is there a way to overwrite the text color manually?

My code looks like this:

`const DatepickerInput = ({ mode = 'date', placeholder = 'select date', onChange }) => {
  const [popupIsVisible, setPopupVisible] = useState(false)
  const [date, setDate] = useState(null)

  const inputDateFormat = mode === 'time' ? 'HH:mm' : 'DD-MM-YYYY'

  return (
    <>
      <TouchableOpacity
        onPress={() => setPopupVisible(true)}
        style={styles.selectDateButton}
      >
        { !date
          ? <Text style={styles.selectDateText}>{placeholder}</Text>
          : <Text>{moment.utc(date).format(inputDateFormat)}</Text>
        }
      </TouchableOpacity>

      <DateTimePickerModal
        isDarkModeEnabled={false}
        isVisible={popupIsVisible}
        mode={mode}
        onConfirm={(value) => {
          setDate(value)
          setPopupVisible(false)
          onChange(value)
        }}
        onCancel={() => setPopupVisible(false)}
        headerTextIOS={placeholder}
        minuteInterval={5}
        useNativeDriver={false}
      />
    </>
  )
}

const styles = StyleSheet.create({
  selectDateButton: {
    width: 340,
    borderColor: '#DDD',
    marginBottom: 20,
    paddingHorizontal: 10,
    borderWidth: 1,
    height: 50,
    fontSize: 20,
    padding: 14
  },
  selectDateText: {
    // color: '#DDD'
  },
})`

**Comment by mmazzarolo** [comment]
@XanderTenBoden are you on `v8.9.0`? `isDarkModeEnabled` should not be required anymore 🤔

**Comment by XanderTenBoden** [comment]
> @XanderTenBoden are you on `v8.9.0`? `isDarkModeEnabled` should not be required anymore 🤔

I'm on version 8.9.1 now. I just tried updating all dependancies and now the behaviour is even more weird. It will stay in dark mode wether or not I set isDarkModeEnabled to true or false, but also when I do remove the whole prop altogether.

**Comment by lukemcgregor** [comment]
Yup remove the whole prop, it now uses the system preference of dark skin or light mode

**Comment by shye0000** [comment]
But what if I wanna force the app to show only the light/dark theme styles?

Imagine that in my app settings for the color theme, I have 3 options: 
- light (will force the color theme to be light and ignore the system color theme)
- dark (will force the color theme to be dark and ignore the system color theme)
- system default (the color theme of the app will follow the system color theme)

**Comment by shye0000** [comment]
Okay, I've found a solution to support the behavior that I've described in my previous comment:
actually we **can** force the text color of the IOS picker by just adding a `textColor` prop which is provided by @react-native-community/datetimepicker to customize its text color and its passed down by this lib

Just do something like this:
```
import DateTimePicker from 'react-native-modal-datetime-picker'

<DateTimePicker
    mode="date"
    isVisible={open}
    **textColor="white"**
    **pickerContainerStyleIOS={styles.pickerContainerStyleIOS}**
/>


pickerContainerStyleIOS: {
      backgroundColor: 'black',
}
```
