### ISSUE TITLE
Support for fontScaling

### ISSUE THREAD

**Issue by saransh-malik** [mmazzarolo/react-native-modal-datetime-picker#497]
## Versions

- Android: 10
- iOS: 13
- react-native-modal-datetime-picker: 9.0.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): 3.0.4
- react-native: 0.63.3
- react:16.13.1

## Description
When we open the modal of datepicker, we have some text components there, which are the Header, cancel button and confirm button. If a user has accessibility on and increased its font size, these font sizes would increase in size too. If we could support a prop that lets user enable or disable fontScaling on these text components.

![image](https://user-images.githubusercontent.com/56735972/100081498-1a26de80-2e6d-11eb-92f3-f5fa04bb8bf9.png)

I can create a PR if you agree for this.

**Comment by mmazzarolo** [comment]
Hey @saransh-malik , thanks for reporting the issue!
Instead of creating a new prop, is this something we can solve directly in the component itself? Our goal here is trying to match the "native" feeling as close as possible, so if we have any chance to do so we're ok with changing it directly in the codebase 👍 
Otherwise, if you need something specific for you app, you can already supply your own custom component as `custom*` props. Let me know!

**Comment by saransh-malik** [comment]
Well my bad, Sorry. I didn't realise we could override those with our custom component. I think that solves the issue. Thanks for your help.
