### ISSUE TITLE
Update react-native-datetimepicker to latest version

### ISSUE THREAD

**Issue by nimabrownlee** [mmazzarolo/react-native-modal-datetime-picker#503]
I'll skip the format as this is very short. https://github.com/react-native-datetimepicker/datetimepicker/issues/247
There is a bug with `textColor` in `react-native-datetimepicker` under version 3.0.0. Could you please update the peerDependency.

**Comment by mmazzarolo** [comment]
@nimabrownlee `peerDependencies` are in your control, you should update them in your local project and `react-native-modal-datetime-picker` will pick-them-up automatically 👍

**Comment by nimabrownlee** [comment]
@mmazzarolo Yep but it doesn't work :/. 

```
  "peerDependencies": {
    "@react-native-community/datetimepicker": "^3.0.8"
  }
```

**Comment by mmazzarolo** [comment]
@nimabrownlee you need to install it directly in your project with `npm i @react-native-community/datetimepicker@3.0.8`

**Comment by nimabrownlee** [comment]
@mmazzarolo I have it both as a dependency and peerDependency. It still does not work unfortunately. Have removed node_modules and reinstalled.

**Comment by nimabrownlee** [comment]
@mmazzarolo Hey, do you have any solution in mind? This bug came up recently and I am stressed about it as we are releasing our map next Tuesday :/.

**Comment by mmazzarolo** [comment]
@nimabrownlee , to clarify:
`@react-native-community/datetimepicker` is a peerDependency of  `react-native-modal-datetime-picker`. 
This means that `react-native-modal-datetime-picker` **does not** install any version of `@react-native-community/datetimepicker`: it will use whatever version of `@react-native-community/datetimepicker` **you** installed. 

If the bug was coming from `@react-native-community/datetimepicker`, there's nothing we can change in this repo to solve it. 

Make sure you installed both libraries correctly and you cleared the cache (`npm run start -- --reset-cache`).

**Comment by renegoretzka** [comment]
I have the same issue with textColor (display="spinner", which works when used without textColor) and newest iOS version. I upgraded to a new version of @react-native-community/datetimepicker, which makes use of this react-native-modal-datetime-picker library.
