### ISSUE TITLE
Better Readme with all Props

### ISSUE THREAD

**Issue by mtsmachado8** [mmazzarolo/react-native-modal-datetime-picker#525]
## Environment
expo

## Platforms
android
ios

## Versions
9.1.0

First of all, thanks a lot for this great lib! I have an idea to making it a little better tough.
I think we could add some infos to README.md
i was facing the DarkMode on ios bug wich made my modal text dark look like this:
![image](https://user-images.githubusercontent.com/11022437/106940884-dbc95d80-6700-11eb-8824-b4edabd0aba2.png)  
There is a lot of issues closed with this problem, i had to go through each one since i couldn't find a way to change this color on the lib props table (Readme). Then i went to source code and i found out that it passes 'otherProps' to '@react-native-community/datetimepicker'
Then i went to that lib to find out wich props were that. only then i found my way to change color (prop textColor) =(
I really think we could increment the props table with the props of '@react-native-community/datetimepicker'.
I dont have a lot of experience with RN or RN Community, so i simply ignored this line:
![image](https://user-images.githubusercontent.com/11022437/106942661-3663b900-6703-11eb-8061-2590a155939b.png)

 I Spent hours on issues and reading after resolving my problem:

```
const colorScheme = Appearance.getColorScheme()
const isDarkModePrefered = colorScheme === 'dark'
  
<DateTimePickerModal
        headerTextIOS="Selecione um horário"
        locale="en_GB"
        mode="time"
        is24Hour={true}
        isVisible={showTimePicker}
        date={value}
        textColor={isDarkModePrefered ? Colors.white : Colors.nightblack}
        isDarkModeEnabled={isDarkModePrefered}
        onCancel={() => setShowTimePicker(false)}
        onConfirm={time => {
          setState({ [valueKey]: time, showTimePicker: false })
        }}
      />
```
![image](https://user-images.githubusercontent.com/11022437/106941821-2697a500-6702-11eb-84b6-31b5c4e1e4ff.png)
![image](https://user-images.githubusercontent.com/11022437/106941859-331bfd80-6702-11eb-93d1-2c4d7a158856.png)

Please consider  making Readme better with those props.
I also think that this should be the default behaviour for handling dark mode.
Let me know if you find this proposal usefull or need any help

**Comment by mmazzarolo** [comment]
Hi @mtsmachado8 ! Thanks for the candid feedback :)
The reason why the README doesn't include all the community picker props, simply put, is because they're not in our control.   
I think there are two issues here:
1) The dark mode issue you're mentioning shouldn't be there if you're using the latest versions of both this picker and the community picker. Are you sure you're using the latest versions of both of them? 
2) We can add some more details to the line of the README you ignored in order to make it easier to understand.

What do you think? I'm open to contributions to the README 👍
