### ISSUE TITLE
isDarkModeEnabled props working in android devices?

### ISSUE THREAD

**Issue by SarvaDev-123** [mmazzarolo/react-native-modal-datetime-picker#535]
## Versions

- Android:
- iOS:
- react-native-modal-datetime-picker:
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker):
- react-native:
- react:

## Description

the calendar opens always the same theme not change when we want to change in dark theme 
or give any suggestion to pass custom color in the theme

**Comment by mmazzarolo** [comment]
`isDarkModeEnabled` is iOS only. Android handles the dark mode UI automatically because the date/time-picker is a native component. If it doesn't, please check how https://github.com/react-native-datetimepicker/datetimepicker handles the android dark/light mode. 
P.S.: I just updated the prop description in the readme 👍
