### ISSUE TITLE
Time doesn't change?

### ISSUE THREAD

**Issue by KemikalGeneral** [mmazzarolo/react-native-modal-datetime-picker#540]
Hi,

Thanks for the library, it works well but I am facing an issue that I hope you can help me with.

I have the datetime picker working on both Android and iOS, but I've just noticed it's not updating the time.

For example, I opened my project at around 10:30 this morning, but now at around 12:40 the time is still showing as 10:30.
If I **reload** Expo, the time will update, but it will stay the same up until I reload it again.

Any idea why this may be happening, please?

Thanks,

**Comment by mmazzarolo** [comment]
Hi @KemikalGeneral, the time doesn't update "live" because it's evaluated the moment the component is mounted. So if you keep the app in the background, it will stay the same. 
Depending on how you're handling your flow, maybe instead of immediately opening the modal when you click on your "show" button (or whatever you're using to opening the modal), in the opening flow you can:
- set a variable in the state with the current time
- use that variable in the `date` prop of the picker, which is the initial date selected in the picker
- **after** the variable has been set, show the picker

Either way, this is a bit out of the scope of the project, so it would be better to ask the question on stackoverflow 👍

**Comment by KemikalGeneral** [comment]
Hi @mmazzarolo,

Sure, thanks for that.
