### ISSUE TITLE
minuteInterval not working

### ISSUE THREAD

**Issue by MaxToyberman** [mmazzarolo/react-native-modal-datetime-picker#56]
Expected behavior:
 passing prop `minuteInterval={15}` should show time in 15 minutes interval.

Actual behavior:
1 minute interval

**Comment by chrismllr** [comment]
@MaxToyberman Is there a reason you closed this? I am having this issue

**Comment by mmazzarolo** [comment]
Hi @chrismllr 

Under the hood react-native-modal-datetime-picker react-native original DatePickerAndroid, TimePickerAndroid and DatePickerIOS.
Try swapping react-native-datetime-picker with react-native original date/time pickers to check if the problem persists.

**Comment by chrismllr** [comment]
@mmazzarolo You're right, the bug seems to be in the native DatePickerIOS... I was able to fix the issue in DatePickerIOS based on this workaround: https://github.com/facebook/react-native/issues/9566#issuecomment-271183941

Unfortunately, the same workaround does not work in the `react-native-modal-datetime-picker` 😕

**Comment by rauldeheer** [comment]
I'm still getting this issue #254
