### ISSUE TITLE
Using Modal datetime-picker Inside Modal make both of them to flickers. 

### ISSUE THREAD

**Issue by Saqib92** [mmazzarolo/react-native-modal-datetime-picker#575]
## Environment

System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
    Memory: 6.74 GB / 15.92 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_291
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms

Currently Testing on ANDROID.

## Versions

- Android: 9+
- iOS:
- react-native-modal-datetime-picker: ^10.0.0
- [react-native-community/datetimepicker](https://github.com/react-native-community/datetimepicker): ^3.5.1
- react-native: 0.64.1
- react: 17.0.1

## Description

Using Datetime picker inside Modal make them both to flickers on date selection. I doubt that backdrop is causing it. 

## Reproducible Demo
Using Date picker inside modal. 
Here is the Github Link for Demo: [Github Repo](https://github.com/Saqib92/react-native-datepicker-with-modal)

**Comment by mmazzarolo** [comment]
Please *fully* follow the issue template

**Comment by Saqib92** [comment]
can you please tell me what actually I am missing apart from Reproducible Demo repo?

**Comment by mmazzarolo** [comment]
Yeah, please see: https://stackoverflow.com/help/minimal-reproducible-example

A repository with the code that isolates the issue is the best way to get your issue investigated. 

(that said, I don't think you can use modal-datetime-picker inside a modal in Android... you can't show multiple modals at the same time).

**Comment by Saqib92** [comment]
Demo for Issue: 
[Github](https://github.com/Saqib92/react-native-datepicker-with-modal)

**Comment by mmazzarolo** [comment]
Thanks, I'm gonna take a look at it. 
From a first glance though, I'm pretty sure the issue is that you can't run multiple modals at the same time on Android in RN: 
- https://github.com/react-native-modal/react-native-modal/issues/171
- https://github.com/react-native-modal/react-native-modal/issues/30

**Comment by mmazzarolo** [comment]
Sorry for being late. I can confirm the issue: it's because we can't have multiple modals running at the same time, yet. It's a RN/Android limitation, and we can't do much on our side to fix it.

**Comment by Saqib92** [comment]
Take a look at this Library if this helps you: 
https://github.com/colorfy-software/react-native-modalfy
