### ISSUE TITLE
Update time picker programmatically

### ISSUE THREAD

**Issue by AliMonam** [mmazzarolo/react-native-modal-datetime-picker#658]
I added a group button on top (customHeaderIOS) of the iOS picker time to have a preset time.
For refreshing the modal I am using key props, but it causes re-opening the modal. Is there any other way to update the picker programmatically without re-opening the modal?

![File](https://user-images.githubusercontent.com/19654690/188775808-b90b8f3d-bad5-434d-b2d9-c2e33d7255a6.jpg)

**Comment by mmazzarolo** [comment]
Hey @AliMonam ! Yeah unfortunately this doesn't seem like something we support nor we plan to support at the moment because it would be an ios-specific thing. On Android you can't change the selected date while the picker is open (and I'm not sure if it's possible even on iOS with the library we're using under the hood). Feel free to play with the repo's code and let me know if you're able to make it work :)

**Comment by mmazzarolo** [comment]
Nope, but we're not doing anything fancy with it. If provided, we'll use it [here](https://github.com/mmazzarolo/react-native-modal-datetime-picker/blob/97da962bed0edcc684620d40e9d13a1ef1f3f631/src/DateTimePickerModal.ios.js#L139) instead of the default datetimepicker component (which is [this one](https://github.com/react-native-datetimepicker/datetimepicker)). So APIs of the `customPickerIOS` and https://github.com/react-native-datetimepicker/datetimepicker should match.
