### ISSUE TITLE
Setting a time range for time picker?

### ISSUE THREAD

**Issue by kirakik** [mmazzarolo/react-native-modal-datetime-picker#87]
I believe that at the moment, it's not possible to set a minimum or maximum time for the time picker, because of limitations on the Android side. Is that something we might be able to see in the future? What about being able to choose a regular list picker for Android time picker, as opposed to the spinner?

**Comment by mmazzarolo** [comment]
Hello @kirakik!  
I'd like to keep the component just as a wrapper around the react-native implementation of the DatePicker/TimePicker (mainly because otherwise I'm 100% sure I wouldn't be able to keep it up to date).  
If you need a feature like that then you have two options I guess:
- Fork this lib and add implement it directly in your own component (I'll gladly link your creation in the README if you're interested)
- If the feature you're requesting is available on the Android TimePicker natively, but still not implemented in react-native, you can directly add it to the react-native codebase. I'm sure it would be a welcome addition 👍
