### ISSUE TITLE
Setting in & out transitions with props AnimationInTiming and AnimationOutTiming

### ISSUE THREAD

**Issue by temitope** [mmazzarolo/react-native-modal-datetime-picker#93]
Is there a way to  use the `AnimationInTiming` prop to set the transition behavior on both iOS and Android (not just iOS props as given by the prop in documentation?). 

Alternatively is there a way to just have the component/UI for the datepicker without having to use it in a modal? (i already have a modal open and would love to just replace the view rather than figure out the timing issue of hiding and showing modals correctly.

I am using version `4.7.0`

**Comment by mmazzarolo** [comment]
Hey @temitope,

> Is there a way to use the AnimationInTiming prop to set the transition behavior on both iOS and Android (not just iOS props as given by the prop in documentation?).

the `animationInTiming` prop can be used only on iOS, since it is a prop of `react-native-modal`,  which is used only on iOS in this component. 

> Alternatively is there a way to just have the component/UI for the datepicker without having to use it in a modal? (i already have a modal open and would love to just replace the view rather than figure out the timing issue of hiding and showing modals correctly.

Are you talking about iOS or Android? Under the hood `react-native-modal-datetime-picker` uses react-native original [DatePickerAndroid](https://facebook.github.io/react-native/docs/datepickerandroid.html), [TimePickerAndroid](https://facebook.github.io/react-native/docs/timepickerandroid.html) and [DatePickerIOS](https://facebook.github.io/react-native/docs/datepickerios.html), so for iOS you can use DatePickerIOS... for Android though, I don't think you can customize the "timing", since it is handled by Android itself.

**Comment by temitope** [comment]
@mmazzarolo  thanks so much for that clarity and promptness. I updated to latest version `4.11.0`

for clarity I was referring to iOS and Android. I will search further. for now I can close this issue for sure. I didnt realize that the animation timing was only for iOS.
